[WIP] Introduce E2E tests
bitrise-io/addons-firebase-testlab pull request #105
Opened 2021-12-02 18:02 UTC by gaborszakacs

2021-12-06 13:52 UTC, viktorbenei requested changes
Comments from our review with TamasP - all files were checked except `e2e_test.go` - tomi will check that ASAP.

2021-12-06 13:52 UTC, viktorbenei commented on e2e/e2e_test.go
> +	client, err := pubsub.NewClient(ctx, pubsubProjectID)
please test the `err` return value

2021-12-06 13:59 UTC, gaborszakacs commented on bitrise.yml
> +  e2e-test-junit-upload:
TBH it is already a bit of a mess, e.g. there's an `android-test` workflow that depends on a server running locally, but I agree that we don't have to add to that :)

2021-12-06 14:01 UTC, gaborszakacs commented on cmd/worker/handle_message.go
> +	logger.Info("message processed:", zap.Any("attributes", m.Attributes))
I thought it could come in handy later too if we want to debug worker issues. There shouldn't be any sensitive data there, I think.  But I'm okay w either should we keep it or lose it? CC @trapacska

2021-12-06 14:04 UTC, gaborszakacs commented on configs/configs.go
> +	const addonConfig = `---
The binary depends on this file being available at this path, which is not a good practice, now we have it when we deploy this to Heroku but it can easily change later on - and it was an issue when putting the binary in a temp folder.

I'm not sure how we use this YML, if it adds value to see the it in YML format, that's why I aimed for the minimal change here, but I don't have a strong opinion.

2021-12-06 14:24 UTC, trapacska requested changes

2021-12-06 14:24 UTC, trapacska commented on e2e/e2e_test.go
> +func initTempDir(t *testing.T) string {
For all occurrences: Is it intentional to not to return error and handle in the Test function but passing `t *testing.T` in helper functions?

2021-12-06 14:24 UTC, trapacska commented on e2e/e2e_test.go
> +
```suggestion
	serverStdout, serverStderr, serverKillFn := startProcess(t, serverCmdPath, envList)
	defer func() {
		err := serverKillFn()
		require.NoError(t, err)
		fmt.Printf("server output:\n")
		fmt.Println(serverStdoutString())
		fmt.Printf("server error output:\n")
		fmt.Println(serverStderr.String())
	}()

	workerStdout, workerStderr, workerKillFn := startProcess(t, workerCmdPath, envList)
	defer func() {
		err := workerKillFn()
		require.NoError(t, err)
		fmt.Printf("worker output:\n")
		fmt.Println(workerStdout.String())
		fmt.Printf("worker error output:\n")
		fmt.Println(workerStderr.String())
	}()

	// Exercise
	runJunitUploadWorkflow(t)

	// Verify
	assertTestReportWasCreated(t)
	assertPubSubMessageWasSent(t, messages)
}

func initTempDir(t *testing.T) string {
	tempPath, err := pathutil.NormalizedOSTempDirPath("temp")
	require.NoError(t, err)

	return tempPath
}

func createPubSubTopicsAndSubscriptions(t *testing.T, ctx context.Context) {
	require.NoError(t, os.Setenv("PUBSUB_EMULATOR_HOST", pubsubServiceBaseURL))
	pubSubClient, err := pubsub.NewClient(ctx, pubsubProjectID)
	require.NoError(t, err)

	defer func() {
		_ = pubSubClient.Close()
	}()

	dataTopic, err := pubSubClient.CreateTopic(ctx, pubsubDataTopicName)
	require.NoError(t, err)

	_, err = pubSubClient.CreateSubscription(ctx, pubsubDataSubscriptionName, pubsub.SubscriptionConfig{
		Topic: dataTopic,
	})
	require.NoError(t, err)

	topic := pubSubClient.Topic(pubsubTopicName)
	ok, err := topic.Exists(ctx)
	require.NoError(t, err)
	if ok {
		return
	}

	topic, err = pubSubClient.CreateTopic(ctx, pubsubTopicName)
	require.NoError(t, err)

	_, err = pubSubClient.CreateSubscription(ctx, pubsubSubscriptionName, pubsub.SubscriptionConfig{
		Topic: topic,
	})
	require.NoError(t, err)
}

func buildProcess(t *testing.T, path, targetPath string) {
	cmd := exec.Command("go", "build", "-o", targetPath, path)
	output, err := cmd.CombinedOutput()
	require.NoError(t, err, string(output))
}

func startProcess(t *testing.T, path string, envs []string) (*bytes.Buffer, *bytes.Buffer, func() error) {
	var (
		stdout, stderr *bytes.Buffer
	)
	
	cmd := exec.Command(path)
	if len(envs) > 0 {
		cmd.Env = envs
	}

	cmd.Stdout = stdout
	cmd.Stderr = stderr

	err := cmd.Start()
	require.NoError(t, err)

	return stdout, stderr, cmd.Process.Kill
}

```

2021-12-06 14:24 UTC, trapacska commented on e2e/e2e_test.go
> +		cmd.Env = envs
fyi: if you override Env then the process will lose envs from system.

2021-12-06 14:24 UTC, trapacska commented on e2e/e2e_test.go
> +
sorry the diff didn't work in the ui editor, here is the diff:
```diff
diff --git a/e2e/e2e_test.go b/e2e/e2e_test.go
index bfcd053..be407be 100644
--- a/e2e/e2e_test.go
+++ b/e2e/e2e_test.go
@@ -1,5 +1,3 @@
-// +build e2e
-
 package e2e
 
 import (
@@ -8,7 +6,6 @@ import (
 	"encoding/json"
 	"fmt"
 	"html/template"
-	"io"
 	"io/ioutil"
 	"net/http"
 	"net/http/httptest"
@@ -85,9 +82,9 @@ func TestJunitUpload(t *testing.T) {
 		err := serverKillFn()
 		require.NoError(t, err)
 		fmt.Printf("server output:\n")
-		printPipe(serverStdout)
+		fmt.Println(serverStdout.String())
 		fmt.Printf("server error output:\n")
-		printPipe(serverStderr)
+		fmt.Println(serverStderr.String())
 	}()
 
 	workerStdout, workerStderr, workerKillFn := startProcess(t, workerCmdPath, envList)
@@ -95,9 +92,9 @@ func TestJunitUpload(t *testing.T) {
 		err := workerKillFn()
 		require.NoError(t, err)
 		fmt.Printf("worker output:\n")
-		printPipe(workerStdout)
+		fmt.Println(workerStdout.String())
 		fmt.Printf("worker error output:\n")
-		printPipe(workerStderr)
+		fmt.Println(workerStderr.String())
 	}()
 
 	// Exercise
@@ -108,16 +105,6 @@ func TestJunitUpload(t *testing.T) {
 	assertPubSubMessageWasSent(t, messages)
 }
 
-func printPipe(pipe *io.ReadCloser) {
-	buf := new(bytes.Buffer)
-	_, err := buf.ReadFrom(*pipe)
-	if err != nil {
-		fmt.Println(err)
-	}
-	fmt.Println(buf.String())
-	buf.Reset()
-}
-
 func initTempDir(t *testing.T) string {
 	tempPath, err := pathutil.NormalizedOSTempDirPath("temp")
 	require.NoError(t, err)
@@ -164,22 +151,23 @@ func buildProcess(t *testing.T, path, targetPath string) {
 	require.NoError(t, err, string(output))
 }
 
-func startProcess(t *testing.T, path string, envs []string) (*io.ReadCloser, *io.ReadCloser, func() error) {
+func startProcess(t *testing.T, path string, envs []string) (*bytes.Buffer, *bytes.Buffer, func() error) {
+	var (
+		stdout, stderr *bytes.Buffer
+	)
+
 	cmd := exec.Command(path)
 	if len(envs) > 0 {
 		cmd.Env = envs
 	}
 
-	stdout, err := cmd.StdoutPipe()
-	require.NoError(t, err)
-
-	stderr, err := cmd.StderrPipe()
-	require.NoError(t, err)
+	cmd.Stdout = stdout
+	cmd.Stderr = stderr
 
-	err = cmd.Start()
+	err := cmd.Start()
 	require.NoError(t, err)
 
-	return &stdout, &stderr, cmd.Process.Kill
+	return stdout, stderr, cmd.Process.Kill
 }
 
 func receiveMessagesSentToDataPubSub(ctx context.Context, t *testing.T, messageCh chan *pubsub.Message) {

```

2021-12-06 14:27 UTC, trapacska commented on cmd/worker/handle_message.go
> +	logger.Info("message processed:", zap.Any("attributes", m.Attributes))
it can stay for debugging reasons, but IMHO a successful message should have other parts we can check for validation, for example a record created for a given build slug etc.

it is really a small detail for me, I would remove it in the longer term and we might keep it till we have couple of debugging sessions

2021-12-06 14:27 UTC, gaborszakacs commented on e2e/e2e_test.go
> +func initTempDir(t *testing.T) string {
Yes, it makes IMO the main code more readable as you don't have to deal with error handling there.

2021-12-06 14:30 UTC, gaborszakacs commented on e2e/e2e_test.go
> +
TBH I just copy-pasted this part from the pipeline spec, I'm not married to it, but it's quite difficult to understand or verify the changes here. Feel free to push a commit to the PR.

2021-12-06 14:33 UTC, trapacska commented on e2e/e2e_test.go
> +func initTempDir(t *testing.T) string {
IMHO to understand the test logic it is easier if we have error handling or execution termination in a single thread rather than put some of these handlings into different branches in the code

2021-12-06 14:38 UTC, gaborszakacs commented on e2e/e2e_test.go
> +		cmd.Env = envs
I guess for this use case it's enough to have the env vars provided, but I can see it causing headaches later on if someone would presume the process has all the current env vars and they just extend it. Wdyt, should we use the orginal envs and append these ones?

2021-12-07 13:20 UTC, gaborszakacs commented on e2e/e2e_test.go
> +		cmd.Env = envs
We don't feel the need to fix this now, resolving.

2021-12-07 13:20 UTC, gaborszakacs commented on configs/configs.go
> +	const addonConfig = `---
This seems to be dead code for now so we can leave it as is.

2021-12-07 13:27 UTC, viktorbenei approved these changes
🤖 👍

2021-12-08 08:22 UTC, merged