[BINS-190] Fix StartedAt timestamp handling, set Build Started At
bitrise-io/addons-firebase-testlab pull request #118
Opened 2021-12-13 16:41 UTC by viktorbenei

2021-12-13 18:03 UTC, viktorbenei commented on cmd/worker/handle_message.go
> +		return errors.Wrap(err, "Failed to get Bitrise build")
seems the DB package does NOT use `pkg/errors` to wrap the error there, so wrapping here

2021-12-13 18:04 UTC, viktorbenei commented on junit/junit_test.go
> +							Message:   "test failure",
this is simply caused by the `junit` package update

2021-12-13 18:05 UTC, viktorbenei commented on pubsubsync/pubsubsync_test.go
> +		"properties": "{\"device_locale\":\"en\",\"device_name\":\"Pixel2\",\"device_orientation\":\"portrait\",\"device_raw\":\"Pixel2-28-en-portrait\",\"device_version\":\"28\",\"tests\":\"3\"}"
this is caused by the `junit` package update

2021-12-13 18:06 UTC, viktorbenei commented on pubsubsync/pubsubsync_test.go
> +			"message": "",
caused by the junit package update

2021-12-13 18:06 UTC, viktorbenei commented on pubsubsync/pubsubsync_test.go
> +			"message": "",
caused by the junit package update

2021-12-13 18:06 UTC, viktorbenei commented on pubsubsync/pubsubsync_test.go
> +   "properties": "{\"device_locale\":\"en\",\"device_name\":\"Pixel2\",\"device_orientation\":\"portrait\",\"device_raw\":\"Pixel2-28-en-portrait\",\"device_version\":\"28\",\"errors\":\"0\",\"failur
caused by the junit package update

2021-12-13 18:14 UTC, viktorbenei commented on pubsubsync/pubsubsync_test.go
> +     "message": "",
caused by the junit package update

2021-12-13 18:14 UTC, viktorbenei commented on pubsubsync/pubsubsync_test.go
> +     "message": "",
caused by the junit package update

2021-12-13 18:14 UTC, viktorbenei commented on pubsubsync/pubsubsync_test.go
> +     "message": "",
caused by the junit package update

2021-12-13 18:15 UTC, trapacska requested changes

2021-12-13 18:15 UTC, trapacska commented on cmd/worker/handle_message.go
> +		return errors.Wrap(err, "Failed to get Bitrise build")
DB package is on child scope, wrapping should happen in parent scope

2021-12-13 18:15 UTC, trapacska commented on pubsubsync/pubsubsync.go
> +	if build.TestStartTime.Valid {
please do nil check before using the pointer model

2021-12-13 18:20 UTC, viktorbenei commented on pubsubsync/pubsubsync.go
> +	if build.TestStartTime.Valid {
this *is* the nil check (we're using `nulls.Time` from `pop` 🤔

2021-12-14 08:39 UTC, gaborszakacs commented on cmd/worker/handle_message.go
> +		return errors.Wrap(err, "Failed to get Bitrise build")
Recording the stack trace should only happen once, preferably closest to when it was returned first, for more context:
https://bitrise.atlassian.net/wiki/spaces/GO/pages/1660452884/Error+handling

2021-12-14 08:44 UTC, gaborszakacs commented on pubsubsync/pubsubsync.go
> +	if build.TestStartTime.Valid {
Tomi meant I guess that `build` itself can be theoretically `nil` here. I'm fine with either, we control the caller so if we're sure we're not passing nil, it can be seen as a bit defensive to check for it.

Ideally I wouldn't pass a pointer here as the struct shouldn't be huge and we don't want to modify it, that would eliminate these kind of discussions too.

2021-12-14 08:50 UTC, gaborszakacs approved these changes

2021-12-14 08:50 UTC, gaborszakacs commented on pubsubsync/pubsubsync_test.go
> +		{
This is out of scope here, just a note: the lack of struct field names makes this test table less readable. CC @trapacska

2021-12-15 13:35 UTC, closed without merging